import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";
import { useEffect, useState } from "react";
import { Input, Image } from "@chakra-ui/react";
import axios from "axios";

interface ICards {
  id: number;
  name: string;
  username: string;
  website: string;
}

interface Props {
  details: ICards[];
}

export default function Home({ details }: Props) {
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [searchResult, setSearchResult] = useState<ICards[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [detailData, setDetailData] = useState<ICards[]>([]);
  const [filter, setFilter] = useState<any>(details);

  // Function to handle value input
  const handleSearch = (event: React.ChangeEvent<HTMLInputElement>) => {
    const term = event?.target.value;
    setSearchTerm(term);

    // Filter the items based on the search terms
    const result = detailData.filter((item) =>
      item.name.toLowerCase().includes(term.toLowerCase())
    );
    console.log(result);
    setSearchResult(result);
    console.log("love", detailData);
  };

  // Function that handles filter
  const filteredData: ICards[] =
    filter === "all"
      ? searchResult
      : searchResult.filter((item) => item.website.includes(filter));

  // Fetch and render the card
  useEffect(() => {
    setLoading(true);
    fetch("https://jsonplaceholder.typicode.com/users?_limit=10")
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        setDetailData(data);
        setLoading(false);
      })
      .catch((error) => {
        setError(error);
        setLoading(false);
      });
  }, []);

  // Set the data to load on refresh
  useEffect(() => {
    setSearchResult(detailData);
  }, [detailData]);

  return (
    <>
      <Head>
        <title>Judith Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {error ? (
        <div className={styles.error}>
          Oops, something went wrong!!! Check your Network
        </div>
      ) : (
        <main className={styles.container}>
          <div className={styles.wrapper}>
            {/* search component */}
            <div className={styles.search_container}>
              <h1 className={styles.search_heading_wrapper}>
                Bio<span>Info</span>
              </h1>
              <div className={styles.search_containers}>
                <Image src="/home/search-icon.svg" alt="search" />
                <div className="form__area">
                  <Input
                    type="text"
                    name="search"
                    placeholder="Search..."
                    value={searchTerm}
                    onChange={handleSearch}
                  />
                </div>
              </div>
              <div className={styles.filter_containers}>
                <div className={styles.filter_wrappers}>
                  <p onClick={() => setFilter("all")}>All</p>
                </div>
                <div className={styles.filter_wrappers}>
                  <p onClick={() => setFilter("info")}>Info</p>
                </div>
                <div className={styles.filter_wrappers}>
                  <p onClick={() => setFilter("org")}>Org</p>
                </div>
                <div className={styles.filter_wrappers}>
                  <p onClick={() => setFilter("com")}>Com</p>
                </div>
              </div>
            </div>
            {/* card component */}
            {filteredData.length > 0  ? 
             (
              <div className={styles.card_container}>
                {filteredData.map((data) => {
                  return (
                    <div className={styles.card_wrapper} key={data.id}>
                      <div className={styles.card_width}>
                        <p>
                          <span>Name:</span> {data.name}
                        </p>
                        <p>
                          <span>Username:</span> {data.username}
                        </p>
                        <p>
                          <span>Website:</span> {data.website}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            ) :
                (<p className={styles.error}>No Result  found</p>)
          }
          </div>
        </main>
      )}
    </>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const details: ICards[] = [];

  return {
    props: {
      details,
    },
  };
};
